"""first migration

Revision ID: 350188c4b73b
Revises: 
Create Date: 2021-08-04 15:23:05.935625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350188c4b73b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sw_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.String(), nullable=False),
    sa.Column('eye_color', sa.String(), nullable=False),
    sa.Column('films', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('hair_color', sa.String(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('homeworld', sa.String(), nullable=False),
    sa.Column('mass', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('skin_color', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('starships', sa.String(), nullable=False),
    sa.Column('vehicles', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sw_people')
    # ### end Alembic commands ###
